// File generated by FlutterFire CLI.
// This is a placeholder. Please run `flutterfire configure` to generate the real file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6UwzyKtvgfl3C9FFCgh1jOx9PCgpZ4Sg',
    appId: '1:1039364391521:web:121196bd7ad8d88112e020',
    messagingSenderId: '1039364391521',
    projectId: 'paracel-network',
    authDomain: 'paracel-network.firebaseapp.com',
    storageBucket: 'paracel-network.firebasestorage.app',
    measurementId: 'G-LWCCBPL579',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhs44ndVEvXIjKIfYmCowGzf0Havu8zHQ',
    appId: '1:1039364391521:ios:05dce3e06543c65412e020',
    messagingSenderId: '1039364391521',
    projectId: 'paracel-network',
    storageBucket: 'paracel-network.firebasestorage.app',
    iosBundleId: 'com.pickpack.pickPack',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhs44ndVEvXIjKIfYmCowGzf0Havu8zHQ',
    appId: '1:1039364391521:ios:05dce3e06543c65412e020',
    messagingSenderId: '1039364391521',
    projectId: 'paracel-network',
    storageBucket: 'paracel-network.firebasestorage.app',
    iosBundleId: 'com.pickpack.pickPack',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCip096EJKRYx7n-FM3pki6TQkVd4_YrN8',
    appId: '1:1039364391521:android:28ce2892797019a912e020',
    messagingSenderId: '1039364391521',
    projectId: 'paracel-network',
    storageBucket: 'paracel-network.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6UwzyKtvgfl3C9FFCgh1jOx9PCgpZ4Sg',
    appId: '1:1039364391521:web:7bb63a3e4008b90d12e020',
    messagingSenderId: '1039364391521',
    projectId: 'paracel-network',
    authDomain: 'paracel-network.firebaseapp.com',
    storageBucket: 'paracel-network.firebasestorage.app',
    measurementId: 'G-57NMYMEXHD',
  );

}